// Fetching
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_CAST = "FETCH_CAST";
export const FETCH_MOVIES_GENRE = "FETCH_MOVIES_GENRE";
export const FETCH_MOVIES_DISCOVER = "FETCH_MOVIES_DISCOVER";
export const FETCH_MOVIES_SEARCH = "FETCH_MOVIES_SEARCH";
export const FETCH_MOVIES_RECOMMENDED = "FETCH_MOVIES_RECOMMENDED";
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
export const FETCH_MOVIESPERSON = "FETCH_MOVIESPERSON";
